spring.application.name=WebshopBackend2

spring.datasource.url=jdbc:postgresql://localhost:5432/webshop_db
spring.datasource.username=postgres
spring.datasource.password=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/webshop_s1156206
#spring.datasource.username=s1156206
#spring.datasource.password=s1156206

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=20000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=10000

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

server.error.include-message=always
server.port=8080
#server.port=26206
server.servlet.context-path=/api
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
